import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// import { SessionProvider, useSession } from "next-auth/react";
import Auth from "./components/Auth";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <SessionProvider session={session}>
        {/* <Auth> */}
        <body className={inter.className}>{children}</body>
        {/* </Auth> */}
      </SessionProvider>
    </html>
  );
}
