import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import SessionProvider from "./components/sessionProvider";
import { getSession } from "next-auth/react";
import Navbar from "./components/navbar";

const font = Source_Code_Pro({ subsets: ["latin"] });
// const inter = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CP-tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={font.className}>
          <Navbar />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
